all:
	dot -Tsvg kset_kobject_ra.dot -o kset_kobject_ra.svg
	dot -Tsvg kobject_struct.dot -o kobject_struct.svg
	dot -Tsvg kobject_uevent.dot -o kobject_uevent.svg
	dot -Tsvg syscall.dot -o syscall.svg
	dot -Tsvg notifier_reboot.dot -o notifier_reboot.svg
	
clean:
	rm -rf *.svg

